# Generated by Django 2.2.6 on 2020-06-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.Book')),
            ],
            options={
                'verbose_name': 'Друг-читатель',
                'verbose_name_plural': 'Друзья-читатели',
                'ordering': ['full_name'],
            },
        ),
    ]
