# Generated by Django 2.2.6 on 2020-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200615_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friend',
            field=models.CharField(default='На скраде', max_length=100, null=True),
        ),
    ]
