# Generated by Django 2.2.6 on 2020-06-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200615_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend'),
        ),
    ]
