# Generated by Django 2.2.6 on 2020-06-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200615_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='books',
        ),
    ]
