# Generated by Django 2.2.6 on 2020-06-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20200615_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.Book'),
        ),
    ]
