# Generated by Django 2.2.6 on 2020-06-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200615_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='book',
        ),
    ]
